import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import styles from '../styles/Home.module.css'
import Header from '../components/header';
import { useRouter } from 'next/router';
import axios from 'axios';
import { useEffect, useState } from 'react';

export default function Home({datas}) {
  const [restaus,setRestaus]=useState([])
  const [id,setId]=useState(null)
  const [loading,setLoading]=useState(false)
  const router=useRouter()
  useEffect( ()=>{
    setLoading(true)
   axios.get('./api/restau/get').then(
      resp=>{
        setRestaus(resp.data)
        console.log(resp.data);
      }
    ).catch(
      e=>{
        console.log(e);
      }
    )
    .finally(()=>setLoading(false))
  
 
    
  },[])

  //console.log(users);
  return (
    <div className='container'>
      <Head>
        <title>Welcome To Chop don done! </title>
        <meta name="description" content="Find wetin di cook :)Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header/>
        <h2>Available Restaurants</h2>
          {loading===true &&(
            <div className="spinner-border" role="status">
              <span className="sr-only"></span>
            </div>
          )}
        <div className='row'>
        {
          
          restaus.map(r=>{
          return(
            <div className='col-11 col-md-4' key={r._id} onClick={()=>{
              router.push({
                pathname:'/restaurant/restaurant',
                asPath:"resturants",
                query:{
                  id:r._id
                }
              })
            }}>
              <div className='card'>
              <Image className='card-img'
              src='https://images.squarespace-cdn.com/content/v1/5e04d1c138bd0a5d714cea2b/1626392332791-5COQ6EK3RC3RD1W1F2IP/achu-served-in-cameroon-cuisine-kengs-kitchen.jpg'
              alt='food'
              width={150}
              height={120}
              />
              <p className='fs-3'>{r.name}</p>
              <p >{r.city}</p>
              </div>
              
            </div>
          )
        })}

        </div>
      <main className={styles.main}>
        <h1 className={styles.title}>
        Welcome To Chop don done!
        </h1>

        <p className={styles.description}>
          Get started with the following steps {' '}
          
        </p>

        <div className='col-sm-12 col-md-8 col-lg-4 mx-auto'>
        <ul className="list-group">
          <li className="list-group-item">Register Your Restaurant</li>
          
          <li className="list-group-item">Customize your page</li>
          <li className="list-group-item">Update Your Menu</li>
          <li className="list-group-item">Wait for Orders</li>
        </ul>
        </div>
      
      
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

/*export async function getServerSideProps(context) {
  
  

  
  const resp =await axios.get('api/hello.js')
  const data= await resp.data
   return{
    props:{
      data:data|| null
    }
  }
 
 // }
  //catch(e){
    //console.log(e);
  //}
  
}*/

